[package]
name = "unity_engine_meta_git_differ"
version = "0.0.0"
edition = "2021"

[dependencies]
git2 = "0.20.2"
ecc_ansi_lib = { git = "https://github.com/Ecconia/RustEccAnsi.git", tag = "v1.0.0" }
